analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    # errors
    - avoid_empty_else
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    # style
    - always_declare_return_types
    - annotate_overrides
    - avoid_classes_with_only_static_members
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_setters_without_getters
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cascade_invocations
    - constant_identifier_names
    - directives_ordering
    - empty_constructor_bodies
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - omit_local_variable_types
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_bool_in_asserts
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - super_goes_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_this
    - use_rethrow_when_possible
    - use_string_buffers
    # pub
    - package_names
